"""Object types available in Scene Studio."""

AVAILABLE_OBJECTS = {
    "alphabet_soup": "AlphabetSoup",
    "bbq_sauce": "BbqSauce",
    "butter": "Butter",
    "cherries": "Cherries",
    "chocolate_pudding": "ChocolatePudding",
    "cookies": "Cookies",
    "corn": "Corn",
    "cream_cheese": "CreamCheese",
    "ketchup": "Ketchup",
    "macaroni_and_cheese": "MacaroniAndCheese",
    "mayo": "Mayo",
    "milk": "Milk",
    "orange_juice": "OrangeJuice",
    "popcorn": "Popcorn",
    "salad_dressing": "SaladDressing",
    "tomato_sauce": "TomatoSauce",
    "white_bowl": "WhiteBowl",
    "akita_black_bowl": "AkitaBlackBowl",
    "plate": "Plate",
    "basket": "Basket",
    "chefmate_8_frypan": "Chefmate8Frypan",
    "glazed_rim_porcelain_ramekin": "GlazedRimPorcelainRamekin",
    "wooden_tray": "WoodenTray",
    "black_book": "BlackBook",
    "yellow_book": "YellowBook",
    "red_coffee_mug": "RedCoffeeMug",
    "porcelain_mug": "PorcelainMug",
    "moka_pot": "MokaPot",
    "wine_bottle": "WineBottle",
    "ball": "Ball",
    "water_ball": "WaterBall",
    "block": "Block",
    "block_small": "BlockSmall",
    "block_large": "BlockLarge",
    "fork": "Fork",
    "candle": "Candle",
    "bottled_water": "BottledWater",
    "kitchen_knife": "KitchenKnife",
    "knife_n": "KnifeN",
    "hammer": "Hammer",
    "hammer_handle": "HammerHandle",
    "scissors": "Scissors",
    "scissors_n": "ScissorsN",
}
